name: pyhf
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _mutex_mxnet=0.0.40=mkl
  - bzip2=1.0.6=h14c3975_5
  - cairo=1.14.12=h8948797_3
  - chardet=3.0.4=py36_1
  - ffmpeg=3.4=h7985aa0_0
  - freeglut=3.0.0=hf484d3e_5
  - graphite2=1.3.12=h23475e2_2
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - idna=2.6=py36h82fb2a8_1
  - intel-openmp=2018.0.3=0
  - jasper=2.0.14=h07fcdf6_1
  - libglu=9.0.0=hf484d3e_1
  - libmklml=2018.0.3=0
  - libmxnet=1.2.1=mkl_hcbe7347_1
  - libopencv=3.4.1=h8fa1ad8_3
  - libopus=1.2.1=hb9ed12e_0
  - libprotobuf=3.5.2=h6f1eeef_0
  - libtiff=4.0.9=he85c1e1_2
  - libvpx=1.7.0=h439df22_0
  - mkl-dnn=0.14=h6bb024c_0
  - mxnet=1.2.1=h8cc8929_0
  - numpy=1.14.3=py36h14a74c5_0
  - pixman=0.34.0=hceecf20_3
  - py-mxnet=1.2.1=py36h6c82189_0
  - pysocks=1.6.8=py36_0
  - requests=2.18.4=py36he2e5f8d_1
  - urllib3=1.22=py36hbe7ace6_0
  - ca-certificates=2018.8.24=ha4d7672_0
  - certifi=2018.8.24=py36_1
  - jq=1.5=4
  - oniguruma=6.8.2=h470a237_1
  - openssl=1.0.2p=h470a237_0
  - appdirs=1.4.3=py36h28b3542_0
  - asn1crypto=0.24.0=py36_0
  - attrs=18.2.0=py36h28b3542_0
  - automat=0.7.0=py36_0
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - bleach=2.1.4=py36_0
  - cffi=1.11.5=py36he75722e_1
  - constantly=15.1.0=py36h28b3542_0
  - cryptography=2.3.1=py36hc365091_0
  - dbus=1.13.2=h714fa37_1
  - decorator=4.3.0=py36_0
  - entrypoints=0.2.3=py36_2
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - glib=2.56.2=hd408876_0
  - gmp=6.1.2=h6c8ec71_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - html5lib=1.0.1=py36_0
  - hyperlink=18.0.0=py36_0
  - icu=58.2=h9c2bf20_1
  - incremental=17.5.0=py36_0
  - ipykernel=4.9.0=py36_0
  - ipython=6.5.0=py36_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.4.1=py36_0
  - jedi=0.12.1=py36_0
  - jinja2=2.10=py36_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=2.6.0=py36_0
  - jupyter=1.0.0=py36_4
  - jupyter_client=5.2.3=py36_0
  - jupyter_console=5.2.0=py36_1
  - jupyter_core=4.4.0=py36_0
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.34=hb9fc6fc_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.8=h26e45fe_1
  - markupsafe=1.0=py36h14c3975_1
  - mistune=0.8.3=py36h14c3975_1
  - mkl=2019.0=117
  - mkl_fft=1.0.4=py36h4414c95_1
  - mkl_random=1.0.1=py36h4414c95_1
  - nbconvert=5.3.1=py36_0
  - nbformat=4.4.0=py36_0
  - ncurses=6.1=hf484d3e_0
  - ninja=1.8.2=py36h6bb024c_1
  - notebook=5.6.0=py36_0
  - numpy-base=1.15.1=py36h81de0dd_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.3.1=py36_0
  - pcre=8.42=h439df22_0
  - pexpect=4.6.0=py36_0
  - pickleshare=0.7.4=py36_0
  - pip=10.0.1=py36_0
  - prometheus_client=0.3.1=py36h28b3542_0
  - prompt_toolkit=1.0.15=py36_0
  - ptyprocess=0.6.0=py36_0
  - pyasn1=0.4.4=py36h28b3542_0
  - pyasn1-modules=0.2.2=py36_0
  - pycparser=2.18=py36_1
  - pygments=2.2.0=py36_0
  - pyopenssl=18.0.0=py36_0
  - pyqt=5.9.2=py36h22d08a2_1
  - python=3.6.6=hc3d631a_0
  - python-dateutil=2.7.3=py36_0
  - pyzmq=17.1.2=py36h14c3975_0
  - qt=5.9.6=h8703b6f_2
  - qtconsole=4.4.1=py36_0
  - readline=7.0=h7b6447c_5
  - send2trash=1.5.0=py36_0
  - service_identity=17.0.0=py36h28b3542_0
  - setuptools=40.2.0=py36_0
  - simplegeneric=0.8.1=py36_2
  - sip=4.19.12=py36he6710b0_0
  - six=1.11.0=py36_1
  - sqlite=3.24.0=h84994c4_0
  - terminado=0.8.1=py36_1
  - testpath=0.3.1=py36_0
  - tk=8.6.8=hbc83047_0
  - tornado=5.1=py36h14c3975_0
  - traitlets=4.3.2=py36_0
  - twisted=18.7.0=py36h14c3975_1
  - wcwidth=0.1.7=py36_0
  - webencodings=0.5.1=py36_1
  - wheel=0.31.1=py36_0
  - widgetsnbextension=3.4.1=py36_0
  - xz=5.2.4=h14c3975_4
  - zeromq=4.2.5=hf484d3e_1
  - zlib=1.2.11=ha838bed_2
  - zope=1.0=py36_1
  - zope.interface=4.5.0=py36h14c3975_0
  - pytorch-cpu=0.4.1=py36_cpu_1
  - pip:
    - absl-py>=0.1.10
    - adal>=1.1.0
    - alabaster>=0.7.11
    - ansiwrap>=0.8.3
    - astor>=0.7.1
    - atomicwrites>=1.2.1
    - azure-datalake-store>=0.0.31
    - azure-nspkg>=2.0.0
    - babel>=2.6.0
    - boto3>=1.9.4
    - botocore>=1.12.4
    - click>=6.7
    - coverage>=4.5.1
    - cycler>=0.10.0
    - docutils>=0.14
    - future>=0.16.0
    - gast>=0.2.0
    - graphviz>=0.9
    - grpcio>=1.15.0
    - imagesize>=1.1.0
    - jmespath>=0.9.3
    - jsonpatch>=1.23
    - jsonpointer>=2.0
    - kiwisolver>=1.0.1
    - latexcodec>=1.0.5
    - m2r>=0.2.0
    - markdown>=2.6.11
    - matplotlib>=2.2.3
    - mock>=2.0.0
    - more-itertools>=4.3.0
    - nbsphinx>=0.3.5
    - oset>=0.1.3
    - packaging>=17.1
    - pandas>=0.23.4
    - papermill>=0.15.0
    - pbr>=4.2.0
    - pluggy>=0.7.1
    - pockets>=0.6.2
    - protobuf>=3.6.1
    - py>=1.6.0
    - py-cpuinfo>=4.0.0
    - pybtex>=0.21
    - pybtex-docutils>=0.2.1
    - pyflakes>=2.0.0
    - pygal>=2.4.0
    - pygaljs>=1.0.1
    - pyjwt>=1.6.4
    - pyparsing>=2.2.0
    - pyrsistent>=0.14.4
    - pytest>=3.8.0
    - pytest-benchmark>=3.1.1
    - pytest-console-scripts>=0.1.5
    - pytest-cov>=2.6.0
    - pytest-runner>=4.2
    - python-coveralls>=2.9.1
    - pytz>=2018.5
    - pyyaml>=3.13
    - s3transfer>=0.1.13
    - scipy>=1.1.0
    - snowballstemmer>=1.2.1
    - sphinx>=1.8.0
    - sphinx-rtd-theme>=0.4.1
    - sphinxcontrib-bibtex>=0.4.0
    - sphinxcontrib-napoleon>=0.6.1
    - sphinxcontrib-websupport>=1.1.0
    - tensorboard>=1.10.0
    - tensorflow>=1.10.1
    - tensorflow-tensorboard>=1.5.1
    - tensorflow-probability==0.3.0
    - termcolor>=1.1.0
    - textwrap3>=0.9.1
    - torch>=0.4.1
    - tqdm>=4.26.0
    - uproot>=3.0.1
    - werkzeug>=0.14.1
